project 'WebScrapping.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebScrapping' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebScrapping
  
  pod 'Alamofire'
  pod 'Kanna', :git => 'https://github.com/tid-kijyun/Kanna', :branch => 'feature/v4.0.0'
  pod 'youtube-ios-player-helper'

end
